apiVersion: v2
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 1.0.0
# https://github.com/paperless-ngx/paperless-ngx/releases
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.20.2

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.5.0
