apiVersion: v2
description: Ubiquiti Network's Unifi Controller
name: unifi
version: 1.0.0
# https://github.com/jacobalberty/unifi-docker/releases
# renovate: image=jacobalberty/unifi
appVersion: v10.0.162

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.5.0
