apiVersion: v2
description: A Helm chart for home-assistant
name: home-assistant
version: 1.0.0
# https://github.com/home-assistant/core/releases
# renovate: image=homeassistant/home-assistant
appVersion: "2025.11.2"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
