apiVersion: v2
description: Monsquitto - lightweight MQTT broker
name: mosquitto
version: 1.0.0

# renovate: image=eclipse-mosquitto
appVersion: 2.0.22

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.0
