apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 1.0.0
appVersion: v1.0.0

dependencies:
- name: traefik
  version: 38.0.1
  repository: https://helm.traefik.io/traefik
