apiVersion: v2
description: A Helm chart for renovatebot
name: renovatebot
version: 1.0.0
# renovate: image=renovate/renovate
appVersion: 42.19.3

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.4.0
